package com.MedveSoft;

import java.net.URL;
import java.net.URLClassLoader;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * A programb�l val� kil�p�s ablak�t jelen�ti meg.
 */
public class DialogOnExit extends javax.swing.JDialog {

    /** A p�rbesz�dablakban be�ll�tott �rt�keket t�rol� t�mb. */
    private Vector returnValues = new Vector();
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if SEND button has been pressed */
    public static final int RET_EXIT_AND_SEND = 1;
    public static final int RET_EXIT_WITHOUT_SEND = 2;

    /** Creates new form NewOkCancelDialog */
    public DialogOnExit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        URLClassLoader urlLoader = (URLClassLoader) GeoProjektor.class.getClassLoader();
        URL url = urlLoader.findResource("icons/program.jpg");
        ImageIcon icon = new ImageIcon(url);
        this.setIconImage(icon.getImage());

        this.setTitle("Kil�p�s");
        this.setLocationRelativeTo(null);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * a p�rbesz�dablak �sszegy�jt�tt adatait adja vissza
     * @return az adatok egy Vector objektumban vannak �sszegy�jtve
     */
    public Vector getReturnValues() {
        returnValues.add(senderEmailUser.getText() + "@gmail.com");
        char[] tempPass = senderEmailPassword.getPassword();
        returnValues.add(new String(tempPass));
        returnValues.add(addresseeEmail.getText());
        returnValues.add(emailSubject.getText());
        returnValues.add(emailBody.getText());

        returnValues.add(supportDevelopment.isSelected());
        returnValues.add(makeArchive.isSelected());

        return returnValues;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        senderEmailUser = new javax.swing.JTextField();
        senderEmailPassword = new javax.swing.JPasswordField();
        addresseeEmail = new javax.swing.JTextField();
        emailSubject = new javax.swing.JTextField();
        supportDevelopment = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emailBody = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        makeArchive = new javax.swing.JCheckBox();
        exitWithoutSendButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        emailSubject.setText("GeoProjektor el�ad�s");

        supportDevelopment.setText("Programfejleszt�s t�mogat�sa m�solat k�ld�s�vel");

        jLabel1.setText("K�ld� email c�me:");

        jLabel2.setText("@gmail.com");

        jLabel3.setText("K�ld� email c�m jelszava:");

        jLabel4.setText("C�mzett email c�me:");

        jLabel5.setText("Email t�rgya:");

        jLabel6.setText("Sz�veges megjegyz�s az emailben:");

        emailBody.setColumns(20);
        emailBody.setLineWrap(true);
        emailBody.setRows(5);
        emailBody.setText("Ez egy automatikusan gener�lt email, melyet a GeoProjektor program k�ld�tt.");
        emailBody.setWrapStyleWord(true);
        jScrollPane1.setViewportView(emailBody);

        sendButton.setText("K�ld�s �s kil�p�s");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Kil�p�s k�ld�s n�lk�l");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        makeArchive.setSelected(true);
        makeArchive.setText("Di�k archiv�l�sa");

        exitWithoutSendButton.setText("M�gse");
        exitWithoutSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitWithoutSendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makeArchive)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senderEmailUser, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senderEmailPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addresseeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(emailSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addComponent(supportDevelopment)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitWithoutSendButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(senderEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(senderEmailPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addresseeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(supportDevelopment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(makeArchive)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(cancelButton)
                    .addComponent(exitWithoutSendButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
    //Bevitt adatok ellen�rz�se
    if (validData()) {
        doClose(RET_EXIT_AND_SEND);
    }
}//GEN-LAST:event_sendButtonActionPerformed

private void exitWithoutSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitWithoutSendButtonActionPerformed
    doClose(RET_CANCEL);
}//GEN-LAST:event_exitWithoutSendButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    doClose(RET_EXIT_WITHOUT_SEND);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
    //dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                DialogOnExit dialog = new DialogOnExit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresseeEmail;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea emailBody;
    private javax.swing.JTextField emailSubject;
    private javax.swing.JButton exitWithoutSendButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox makeArchive;
    private javax.swing.JButton sendButton;
    private javax.swing.JPasswordField senderEmailPassword;
    private javax.swing.JTextField senderEmailUser;
    private javax.swing.JCheckBox supportDevelopment;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    /**
     * Ellen�rzi, hogy megfelel� adatokat adott-e meg a felhaszn�l� �s hiba�zenettel t�j�koztat, ha nem.
     * @return TRUE vagy FALSE att�l f�gg�en, hogy az adatok �rv�nyesek-e
     */
    private boolean validData() {
        boolean valid = true;
        String aEmail = addresseeEmail.getText();
        String sEmail = senderEmailUser.getText();
        char[] tempStr = senderEmailPassword.getPassword();
        String sEmailPass = new String(tempStr);

        if (aEmail.isEmpty() | sEmail.isEmpty() | sEmailPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nem adott meg minden adatot az email elk�ld�s�hez!", "Hiba!", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (!aEmail.contains("@") | !aEmail.contains(".")) {
            JOptionPane.showMessageDialog(this, "Hib�s a c�mzett emailc�me!", "Hiba!", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (sEmail.contains("@")) {
            JOptionPane.showMessageDialog(this, "Technikai okok miatt a k�ld� emailc�me csak Gmail-es emailc�m lehet!\nA '@' karakter ut�ni r�szt nem kell megadnia a k�ld� emailc�m eset�ben!", "Hiba!", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        return valid;
    }
}
